name: nddl
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.10.12
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.66.6
      - numpy==1.26.4
      - pandas==2.2.2
      - seaborn==0.13.2
      - matplotlib==3.8.0
      - ipykernel