[network]
use_alif_neurons = true  
clf_alpha = 1.0
energy_alpha = 0.05  
spike_alpha = 0.0 
one_to_one = true
lr = 0.001
p_dropout = 0.4
is_recurrent = false
b0 = 0.1 
d_in = 784
d_hidden = [600, 500, 500]
n_classes = 10

[training]
n_batch = 256
T = 50
K = 10  
clip = 1.0
log_interval = 20
epochs = 35
alpha = 0.2
beta = 0.5
rho = 0.0

[decoder]
recon_alpha = 0.0
decoder_layer = 1
